services:
  php-nginx:
    build: .
    container_name: air-saas
    ports:
      - "8000:80"
      - "5173:5173"
    volumes:
      - ./:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
    depends_on:
      - db
    user: "${UID}:${GID}"

  db:
    image: mysql:8.0
    ports:
      - ${DB_ALTERNATIVE_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
