services:
  php-nginx:
    build: .
    container_name: air-saas
    ports:
      - "8000:80"
      - "5173:5173"
    volumes:
      - ./:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: